apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-nginx
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: nginx
        ports:
        - containerPort: 80
          hostPort: 8091
