apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todo-dev

resources:
  - namespace.yaml
  - ../../base

namePrefix: dev-

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: test-nginx
