apiVersion: v1
kind: Namespace
metadata:
  name: todo-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dev
  namespace: todo-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-dev
  template:
    metadata:
      labels:
        app: todo-app-dev
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
        env:
        - name: WEATHER_API_KEY
          valueFrom:
            secretKeyRef:
              name: weather-api-secret
              key: api-key
        - name: WEATHER_API_URL
          valueFrom:
            secretKeyRef:
              name: weather-api-secret
              key: api-url
        volumeMounts:
        - name: html-config
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-config
        configMap:
          name: weather-html-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: weather-html-config
  namespace: todo-dev
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Weather App - Linz, Austria</title>
        <style>
            body { 
                font-family: Arial, sans-serif; 
                margin: 40px; 
                background: #f5f5f5; 
                color: #333;
            }
            .container { 
                max-width: 500px; 
                margin: 0 auto; 
                background: white; 
                padding: 30px; 
                border-radius: 8px; 
                box-shadow: 0 2px 10px rgba(0,0,0,0.1); 
            }
            h1 { 
                text-align: center; 
                color: #2c3e50; 
                margin-bottom: 30px; 
            }
            .info-box { 
                background: #3498db; 
                color: white; 
                padding: 20px; 
                border-radius: 5px; 
                margin: 20px 0; 
            }
            .weather-data { 
                background: #27ae60; 
                color: white; 
                padding: 20px; 
                border-radius: 5px; 
                margin: 20px 0; 
            }
            .secret-status { 
                background: #e74c3c; 
                color: white; 
                padding: 15px; 
                border-radius: 5px; 
                margin: 20px 0; 
                text-align: center; 
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>Weather App - Linz, Austria</h1>
            
            <div class="info-box">
                <h3>GitOps Secrets Management Demo</h3>
                <p>This app uses an encrypted Kubernetes secret stored in Git.</p>
                <p>API key is securely injected from sealed secret.</p>
            </div>
            
            <div class="weather-data">
                <h3>Current Weather - Linz, Austria</h3>
                <p>Temperature: 15°C</p>
                <p>Conditions: Partly Cloudy</p>
                <p>Humidity: 65%</p>
                <p>Wind: 3.2 m/s</p>
            </div>
            
            <div class="secret-status">
                <strong>Secret Status: Loaded from Kubernetes</strong>
            </div>
            
            <p style="text-align: center; color: #7f8c8d; margin-top: 30px;">
                <em>Deployed via GitOps with Argo CD</em>
            </p>
        </div>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: todo-app-dev
  namespace: todo-dev
spec:
  selector:
    app: todo-app-dev
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: todo-app-dev-external
  namespace: todo-dev
spec:
  selector:
    app: todo-app-dev
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30091
  type: NodePort