apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: weather-api-secret
  namespace: todo-dev
spec:
  encryptedData:
    api-key: AgCYCtp41nM7Dga6qLK4eWB+iNr+dMe83If8MQl4RyUMCn1hJokvn00zFgMc9w7b6ha7AjmlJJ7EnqqrRU8xdchPakUmo98bVrcltA3r93JMQFWw259l9eh5kPQJMpKmTacfIZWtY0KS8GNkvurinzQMel1Zwif1SZm/XHzW+2rgCpKodVQZQS55DQJ7gMM6u/idMt8hzDsF/O9UbzIyMLY0hSkN7/DlTgC7uDbvqweTdnLbpdXMasJbX77KveXwUTbeXsiilQx/loAtoKLkCoJePeBbwBljSNYuWPsALCBLGITEkwY7eKZmDvXIWWrg5ZS5n+ITmiIeeCLG21Jd4Y1oBDV9WBIy388+ZRHDkMuQEXicDlaNW8ZRqonhwjeOmt4HotJS9SeXdBbRjb/BEWpoWzrO3L0MQwH929eHZ4pdPbRRqgmdCh+xbio79kqKBdkoEPoOYhXMnToAGqptH06ObcnbCEiUVP4aj3bbbYsoJ4f25YxAc+QQ+7canGdZ+CCEcbUioFnIV7QDIMWQbafrpoYOI7Hrbw8U+RJQjBUBk6tv59DXHLAgCQOftQpwhp41i2eBjp/bNv6XYt0dI6/6neTZpZSy7QxbGApqCME3TZDPd9PwJ/u7X1eJlMGX/Y/XqKRXHZwg8wSzwkQFHTq5VHvvc7YhdaKR6x45eG7L3OJM+UFauxLeF3EF46EtgwjkPCqE7jDzpHOjQZMS1aW9XyV/aej2qSXeFbRy/JOoyA==
    api-url: AgCDBH4j0E0aV3Vk7qs4mdz6pMtNPPH4a6P6ZbhF+/IEmH3QuRVWc1qHmdnKNuk0RTfmOZC92XrAla+VP284eK49mRIKBouDlgqsnMIFw7Lrl5Kgv00ZL2MMXlxYjbp/23x+jMBFvQMkDNuaoNVKDBAp4Z6pFVIqi1z6aLV4dXbY55vZBKwi0fO6k/X9u7PVHOkVOQaIX6O5xZMSJpa/GvCqgfG9d3j8svpZ6H2A4h/KZW878YW5rliQxvzg8RDT64FBBhP2Pk/hXypYI6Z8Hp1Uc0TppucAZw6/9oOnFTc6hwby+Iboo0J6SuAndYKVJT9EKo8gEk84rXzoDCSJgBYIof1VUyUIjNKdkaz4iE0kB+1OSxYPTa8r2GcUn06sQCQz2ea0rmOL0plJEWZjDIsDGQEzu9EmBiMSX9MX+aF+73ENEdk0W2BTCiQdleUbCHOXQuxmOGY+dZcsKDmCES/nNOudFZkGp9dWLImDUyt2m2omBmord6CpbumRkGKaBVMRT/IecFFi5plvWQ/3EAKwr8C81P7C79dNlnwwQnvvvM12gQ86konU2dcj4CkbC6pQ16kmXVpdbLGiYAbuYY8JwKNqSgGtJLb3z0BfN1lqy81+kVn4ScPdIhnlw5h4U5K1YcMWggD2h1rHDmZ44I4fSX/2balHHhHSsltgtDzv4tb8WrYLVt/fuiqgtNrbfH9oDrTfeS/DiZCYr3rmNm0pni+C4D9bI5fuxUdPk1sK0bHnDi6rOYW6m7eMv35feD9RX1bWli1b4IqHwdyBYkRavx9056D2
  template:
    metadata:
      creationTimestamp: null
      name: weather-api-secret
      namespace: todo-dev
---